"""waypoint_rules: every constraint, calculation and refusal message, in one place.

Pure Python, standard library only. No FastAPI, no SQLAlchemy. Used by the API, the seed
checks and the Datathon notebook (PRD v3 §11). The frontend never re-implements a rule: it
asks the API, which asks this package.
"""

from .calc import StopTiming, TripClock, TripFuel, hhmm, planned_clock, planned_fuel, trip_load, trip_minutes
from .constraints import (
    Violation,
    check_trip,
    check_vehicle_day,
    legal_vehicles,
    order_vehicle_violations,
    vehicle_day_totals,
)
from .deferrals import (
    BindingResult,
    DeferredMinutes,
    Frees,
    Impact,
    MinutesPool,
    SwapRecommendation,
    TripMinutes,
    binding_resource,
    classify_deferral,
    frees,
    headline,
    impact_on_store,
    minutes_pools,
    recommend_swap,
    scarcest_pool,
)
from .lifecycle import IllegalTransition, OrderEvent, allowed_events, transition
from .model import District, Order, Outlet, Plan, RefData, Trip, Vehicle, VehicleDay
from .moves import CheckItem, Move, MoveResult, TripSummary, validate_move, why_this_vehicle
from .planner import DraftDeferral, DraftStop, DraftTrip, OutletHistory, PlanDraft, draft_plan
from .reconcile import (
    DeviceRecord,
    Outcome,
    Recommendation,
    Reconciled,
    RecordType,
    ServerOrderState,
    SyncResult,
    reconcile,
    reconcile_store_answer,
)
from .schedule import (
    OFFLINE_AFTER_MINUTES,
    RemainingStop,
    ServiceDay,
    is_offline,
    lateness_risk,
    next_plan_at,
    service_day_for,
    store_arrival,
)
from .vocab import (
    Binding,
    Brand,
    DeferralType,
    DockType,
    LatenessRisk,
    OrderStatus,
    Role,
    RuleId,
    Temp,
    VehicleTemp,
    VehicleType,
    status_label,
)

__all__ = [
    "Binding",
    "BindingResult",
    "Brand",
    "CheckItem",
    "DeferralType",
    "DeferredMinutes",
    "DeviceRecord",
    "District",
    "DraftDeferral",
    "DraftStop",
    "DraftTrip",
    "DockType",
    "Frees",
    "IllegalTransition",
    "Impact",
    "LatenessRisk",
    "Move",
    "MinutesPool",
    "MoveResult",
    "OFFLINE_AFTER_MINUTES",
    "Order",
    "OrderEvent",
    "OrderStatus",
    "Outcome",
    "Outlet",
    "OutletHistory",
    "Plan",
    "PlanDraft",
    "Recommendation",
    "Reconciled",
    "RecordType",
    "RefData",
    "RemainingStop",
    "Role",
    "RuleId",
    "ServerOrderState",
    "ServiceDay",
    "StopTiming",
    "SwapRecommendation",
    "SyncResult",
    "Temp",
    "Trip",
    "TripClock",
    "TripFuel",
    "TripMinutes",
    "TripSummary",
    "Vehicle",
    "VehicleDay",
    "VehicleTemp",
    "VehicleType",
    "Violation",
    "allowed_events",
    "binding_resource",
    "check_trip",
    "check_vehicle_day",
    "classify_deferral",
    "draft_plan",
    "frees",
    "headline",
    "hhmm",
    "is_offline",
    "impact_on_store",
    "lateness_risk",
    "legal_vehicles",
    "minutes_pools",
    "next_plan_at",
    "order_vehicle_violations",
    "planned_clock",
    "planned_fuel",
    "reconcile",
    "reconcile_store_answer",
    "recommend_swap",
    "scarcest_pool",
    "service_day_for",
    "status_label",
    "store_arrival",
    "transition",
    "trip_load",
    "trip_minutes",
    "validate_move",
    "vehicle_day_totals",
    "why_this_vehicle",
]
