"""waypoint_rules: every constraint, calculation and refusal message, in one place.

Pure Python, standard library only. No FastAPI, no SQLAlchemy. Used by the API, the seed
checks and the Datathon notebook (PRD v3 §11). The frontend never re-implements a rule: it
asks the API, which asks this package.
"""

from .calc import StopTiming, TripClock, TripFuel, hhmm, planned_clock, planned_fuel, trip_load, trip_minutes
from .constraints import (
    Violation,
    check_trip,
    check_vehicle_day,
    legal_vehicles,
    order_vehicle_violations,
    vehicle_day_totals,
)
from .deferrals import (
    BindingResult,
    Frees,
    Impact,
    SwapRecommendation,
    binding_resource,
    classify_deferral,
    frees,
    headline,
    impact_on_store,
    recommend_swap,
)
from .lifecycle import IllegalTransition, OrderEvent, allowed_events, transition
from .model import District, Order, Outlet, Plan, RefData, Trip, Vehicle, VehicleDay
from .moves import CheckItem, Move, MoveResult, TripSummary, validate_move, why_this_vehicle
from .reconcile import (
    DeviceRecord,
    Outcome,
    Recommendation,
    Reconciled,
    RecordType,
    ServerOrderState,
    SyncResult,
    reconcile,
)
from .schedule import RemainingStop, ServiceDay, lateness_risk, service_day_for, store_arrival
from .vocab import (
    Binding,
    Brand,
    DeferralType,
    DockType,
    LatenessRisk,
    OrderStatus,
    Role,
    RuleId,
    Temp,
    VehicleTemp,
    VehicleType,
    status_label,
)

__all__ = [
    "Binding",
    "BindingResult",
    "Brand",
    "CheckItem",
    "DeferralType",
    "DeviceRecord",
    "District",
    "DockType",
    "Frees",
    "IllegalTransition",
    "Impact",
    "LatenessRisk",
    "Move",
    "MoveResult",
    "Order",
    "OrderEvent",
    "OrderStatus",
    "Outcome",
    "Outlet",
    "Plan",
    "Recommendation",
    "Reconciled",
    "RecordType",
    "RefData",
    "RemainingStop",
    "Role",
    "RuleId",
    "ServerOrderState",
    "ServiceDay",
    "StopTiming",
    "SwapRecommendation",
    "SyncResult",
    "Temp",
    "Trip",
    "TripClock",
    "TripFuel",
    "TripSummary",
    "Vehicle",
    "VehicleDay",
    "VehicleTemp",
    "VehicleType",
    "Violation",
    "allowed_events",
    "binding_resource",
    "check_trip",
    "check_vehicle_day",
    "classify_deferral",
    "frees",
    "headline",
    "hhmm",
    "impact_on_store",
    "lateness_risk",
    "legal_vehicles",
    "order_vehicle_violations",
    "planned_clock",
    "planned_fuel",
    "reconcile",
    "recommend_swap",
    "service_day_for",
    "status_label",
    "store_arrival",
    "transition",
    "trip_load",
    "trip_minutes",
    "validate_move",
    "vehicle_day_totals",
    "why_this_vehicle",
]
